name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
env:
    NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: 'Pack Project'
      run: dotnet pack --configuration Release
    - name: 'Push package'
      run: dotnet nuget push 'src/Aqua.StringHelpers/bin/Release/*.nupkg' -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}

    
